[2024-07-04T13:04:05.795+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-04T13:04:05.808+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_transformation.data_extraction scheduled__2024-07-03T00:00:00+00:00 [queued]>
[2024-07-04T13:04:05.814+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_transformation.data_extraction scheduled__2024-07-03T00:00:00+00:00 [queued]>
[2024-07-04T13:04:05.814+0530] {taskinstance.py:2306} INFO - Starting attempt 4 of 5
[2024-07-04T13:04:05.834+0530] {taskinstance.py:2330} INFO - Executing <Task(HttpOperator): data_extraction> on 2024-07-03 00:00:00+00:00
[2024-07-04T13:04:05.842+0530] {standard_task_runner.py:63} INFO - Started process 92888 to run task
[2024-07-04T13:04:05.847+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_transformation', 'data_extraction', 'scheduled__2024-07-03T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp6iuqi_qw']
[2024-07-04T13:04:05.850+0530] {standard_task_runner.py:91} INFO - Job 5: Subtask data_extraction
[2024-07-04T13:04:05.905+0530] {task_command.py:426} INFO - Running <TaskInstance: data_transformation.data_extraction scheduled__2024-07-03T00:00:00+00:00 [running]> on host ongraph-Lenovo-V130-14IKB
[2024-07-04T13:04:05.985+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rohit' AIRFLOW_CTX_DAG_ID='data_transformation' AIRFLOW_CTX_TASK_ID='data_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-03T00:00:00+00:00'
[2024-07-04T13:04:05.986+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-04T13:04:06.002+0530] {http.py:169} INFO - Calling HTTP method
[2024-07-04T13:04:06.009+0530] {base.py:84} INFO - Using connection ID 'http_connection' for task execution.
[2024-07-04T13:04:06.036+0530] {base.py:84} INFO - Using connection ID 'http_connection' for task execution.
[2024-07-04T13:04:07.729+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-04T13:04:07.731+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ongraph/Desktop/airflow/airflow_ETL/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ongraph/Desktop/airflow/airflow_ETL/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ongraph/Desktop/airflow/airflow_ETL/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ongraph/Desktop/airflow/airflow_ETL/venv/lib/python3.10/site-packages/airflow/providers/http/operators/http.py", line 166, in execute
    return self.execute_sync(context=context)
  File "/home/ongraph/Desktop/airflow/airflow_ETL/venv/lib/python3.10/site-packages/airflow/providers/http/operators/http.py", line 172, in execute_sync
    return self.process_response(context=context, response=response)
  File "/home/ongraph/Desktop/airflow/airflow_ETL/venv/lib/python3.10/site-packages/airflow/providers/http/operators/http.py", line 215, in process_response
    return self.response_filter(response, **kwargs)
  File "/home/ongraph/Desktop/airflow/airflow_ETL/dags/etl.py", line 31, in <lambda>
    response_filter= lambda response : json.loads(response).get('newspapers')
  File "/usr/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not Response
[2024-07-04T13:04:07.755+0530] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_transformation, task_id=data_extraction, run_id=scheduled__2024-07-03T00:00:00+00:00, execution_date=20240703T000000, start_date=20240704T073405, end_date=20240704T073407
[2024-07-04T13:04:07.810+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task data_extraction (the JSON object must be str, bytes or bytearray, not Response; 92888)
[2024-07-04T13:04:07.827+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-04T13:04:07.852+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-04T13:04:07.853+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
